### ISSUE TITLE
https://opentokrtc.com  is not working  in Microsoft Edge

### ISSUE THREAD

**Issue by prabhakarreddy1234** [opentok/opentok-rtc#444]
When i try to open https://opentokrtc.com  in Microsoft Edge. Browser gets refreshed 3 times and then browser instance is corrupted.    Not sure if this is the right place to ask this question. Please point me in the right direction.

**Comment by rhainer** [comment]
@prabhakarreddy1234 - Thank you for reporting the issue. MS Edge is not yet a supported browser for this application. It is on our roadmap and we welcome input, analysis, and pull requests from the community.

**Comment by miksansegundo** [comment]
This issue is still open nowadays when TokBox is in beta support for MS Edge 17+ https://tokbox.com/developer/beta/edge/

Could anyone please confirm the MS Edge support situation nowadays?

**Comment by ggoldens** [comment]
@MichaelKelleher @prabhakarreddy1234 Do you still see the issue in MS edge?
I just tested it and it seems to be working as expected. Here you have a screenshot of my test:
![MS edge opentok](https://user-images.githubusercontent.com/10964589/59375687-15c43f80-8d25-11e9-9155-229ee29bce57.jpeg)
Please confirm this so that we can close this issue. Thanks!
